---
title: "project term 3"
output:
  word_document: default
  html_document: default
date: "2024-05-28"
editor_options:
  markdown:
    wrap: 72
---

```{r setup}
library("dplyr")
library("ggplot2")
library("tidyverse")
library("afex")
library("lme4")# for multilevel models
library("lmerTest") # for p-values
library("performance") # for ICC
library("tibble")
library("readr")
install.packages("here")
library("here")

getwd()
data <- read.csv(here("CEDS.csv"))
theme_set(theme_bw(base_size = 15) + theme(legend.position="bottom"))
str(data)
summary(data)
```

```{r get required columns and identify missing ons}
required_columns <- c(
  "ID", "riskHI", "tleltpca", "Saliva1Time", "Saliva2Time", "Saliva3Time", "Saliva4Time", "Saliva5Time", "Saliva6Time",
  "echrdpa", "SESA"
)
# Check if all required columns are present
missing_columns <- setdiff(required_columns, colnames(data))
if(length(missing_columns) > 0) {
  stop("The following required columns are missing from the dataset: ", paste(missing_columns, collapse = ", "))
}
```

```{r creat a new dataset}
# Create a new dataset, saliva7time is neglected because in the original document it is stated that the variability in this sample is too great, and it is not typically used.
datasub <- data %>%
  select(ID, echrdpa, SESA, tleltpca, riskHI, Saliva1Time, Saliva2Time, Saliva3Time, Saliva4Time, Saliva5Time, Saliva6Time)
print(datasub)
view(datasub)
```

```{r transform continuous riskHI to categorical riskgroup}
datasub$riskgroup <- factor(datasub$riskHI, levels = c(0, 1), labels = c("moderate_low_risk", "high_risk"))
print(datasub)
```

```{r rename}
datasub <- datasub %>% 
  rename(financial_hardship = echrdpa,
         SES = SESA,
         trauma_lifetime = tleltpca)
view(datasub)
```

```{r clean data}
# Remove rows with NA values
datasubset <- datasub %>% drop_na(ID, financial_hardship, SES, trauma_lifetime, riskHI, Saliva1Time, Saliva2Time, Saliva3Time, Saliva4Time, Saliva5Time, Saliva6Time)
view(datasubset)
```

```{r visualizations}
# Histogram without NA values
ggplot(datasubset, aes(x =Saliva1Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 1 without NA values")

ggplot(datasubset, aes(x =Saliva2Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 2 without NA values")

ggplot(datasubset, aes(x =Saliva3Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 3 without NA values")

ggplot(datasubset, aes(x =Saliva4Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 4 without NA values")

ggplot(datasubset, aes(x = Saliva5Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 5 without NA values")

ggplot(datasubset, aes(x =Saliva6Time)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  ggtitle("Histogram 6 without NA values")
```


```{r Shapiro-Wilk test for normality}
results <- list() 
columns <- c("Saliva1Time", "Saliva2Time", "Saliva3Time", "Saliva4Time", "Saliva5Time", "Saliva6Time")

for (col in columns) {
  results[[col]] <- shapiro.test(datasubset[[col]])
}

print(results)
```

```{r Descriptive stats}
descriptive_stats <- datasubset %>%
  group_by(riskgroup) %>%
  summarize(
    mean_financ = mean(financial_hardship, na.rm = TRUE),
    sd_financ = sd(financial_hardship, na.rm = TRUE),
    mean_SES = mean(SES, na.rm = TRUE),
    sd_SES = sd(SES, na.rm = TRUE),
    mean_traumalifetime = mean(trauma_lifetime, na.rm = TRUE),
    sd_traumalifetime = sd(trauma_lifetime, na.rm = TRUE),
    mean_time1 = mean(Saliva1Time, na.rm = TRUE),
    sd_time1 = sd(Saliva1Time, na.rm = TRUE),
    mean_time2 = mean(Saliva2Time, na.rm = TRUE),
    sd_time2 = sd(Saliva2Time, na.rm = TRUE),
    mean_time3 = mean(Saliva3Time, na.rm = TRUE),
    sd_time3 = sd(Saliva3Time, na.rm = TRUE),
    mean_time4 = mean(Saliva4Time, na.rm = TRUE),
    sd_time4 = sd(Saliva4Time, na.rm = TRUE),
    mean_time5 = mean(Saliva5Time, na.rm = TRUE),
    sd_time5 = sd(Saliva5Time, na.rm = TRUE),
    mean_time6 = mean(Saliva6Time, na.rm = TRUE),
    sd_time6 = sd(Saliva6Time, na.rm = TRUE),
  )
print(descriptive_stats)
```



```{r Create a longitudinal data format}
install.packages("labelled") 
library("labelled")
data_long <- pivot_longer(datasubset, cols = starts_with("Saliva"), 
                            names_to = "measurement", values_to = "distance") %>% 
  mutate(
    timepoint = parse_number(measurement),
    measurement = fct_inorder(paste("Measure at timepoint", timepoint))
  ) %>% 
  set_variable_labels(
    timepoint = "timepoints of cortisol measurement",
    measurement = "Label for time measurement",
    distance = "Measurement"
  )

head(data_long)
```

```{r mean response over time}
summary_stats <- data_long %>%
  group_by(timepoint) %>%
  summarize(
    mean_distance = mean(distance, na.rm = TRUE),
    sd_distance = sd(distance, na.rm = TRUE),
    min_distance = min(distance, na.rm = TRUE),    
    max_distance = max(distance, na.rm = TRUE), 
    median_distance = median(distance, na.rm = TRUE),
    count = n(),
    .groups = 'drop')
print(summary_stats)
write.xlsx(summary_stats, "~/Desktop/summary_stats.xlsx")
```

```{r a box plot}
ggplot(data_long, aes(riskgroup, distance, fill = measurement)) +
  geom_boxplot() +
  labs(x = "", y = "cortisol level", fill = "")
```

```{r a trajectory plot}
summary_stats <- data_long %>%
  group_by(riskgroup, timepoint) %>%
  summarise(
    mean_distance = mean(distance, na.rm = TRUE),
    sd_distance = sd(distance, na.rm = TRUE),
    count = n(),
    se_distance = sd_distance / sqrt(count), 
    ymin = mean_distance - 1.96 * se_distance,  
    ymax = mean_distance + 1.96 * se_distance, 
    .groups = "drop"
  )

ggplot(summary_stats, aes(x = timepoint, y = mean_distance, color = riskgroup, shape = riskgroup)) +
  geom_point(position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0.2, position = position_dodge(width = 0.1)) +
  geom_line(aes(group = riskgroup)) +
  labs(x = "Timepoint", y = "Cortisol Level", color = "Risk Group", shape = "Risk Group")
```

```{r Log transformation}
## To make it normally distributed
data_long <- data_long %>%
mutate(distance_log = log(distance+1)) 
```

```{r models}
# To test hypothesis 1: Effect of Parenting Style on Transformed Cortisol Reactivity
model1 <- lmer(distance_log ~ riskHI + SES + financial_hardship + (1|ID), data = data_long)
summary(model1)

# To test hypothesis 2: Effect of Traumatic Events on Transformed Cortisol Reactivity
model2 <- lmer(distance_log ~ trauma_lifetime + SES + financial_hardship + (1|ID), data = data_long)
summary(model2)

# To test hypothesis 3: Interaction Effect between Parenting Style and Traumatic Events on Transformed Cortisol Reactivity
model3 <- lmer(distance_log ~ riskHI * trauma_lifetime + SES + financial_hardship + (1|ID), data = data_long)
summary(model3)
```

```{r model comparison}
anova(model1, model2, model3)

icc_model1 <- icc(model1)
icc_model2 <- icc(model2)
icc_model3 <- icc(model3)

print(icc_model1)
print(icc_model2)
print(icc_model3)
```

